- packages/dicebag/dicebag-0.0.3.d.ts
- packages/dicebag/dicebag.d.ts
- packages/dicebag/library.json
https://github.com/8bitskull/dicebag
> feat: dicebag

- packages/defsave/defsave-1.2.4.d.ts
- packages/defsave/defsave.defsave.d.ts
- packages/defsave/library.json
[Package](https://github.com/subsoap/defsave)
> [defsave] Add defsave 1.2.4 package

- packages/extension-crypt/crypt-1.0.2.d.ts
- packages/extension-crypt/crypt.d.ts
- packages/extension-crypt/library.json
[Package](https://github.com/defold/extension-crypt)
> [extension-crypt] Add extension-crypt package

- packages/defold-xmath/library.json
- packages/defold-xmath/xmath-0.0.1.d.ts
- packages/defold-xmath/xmath.d.ts
Adds [defold-xmath](https://github.com/thejustinwalsh/defold-xmath)
> Add defold-xmath

- packages/JsToDef/JsToDef-2.0.0.d.ts
- packages/JsToDef/JsToDef.d.ts
- packages/JsToDef/library.json
- packages/extension-vibrate/extension-vibrate-0.2.1.d.ts
- packages/extension-vibrate/extension-vibrate.d.ts
- packages/extension-vibrate/library.json
- packages/pcgrandom/library.json
- packages/pcgrandom/pcgrandom-1.2.6.d.ts
- packages/pcgrandom/pcgrandom.d.ts
- packages/review/library.json
- packages/review/review-3.2.0.d.ts
- packages/review/review.d.ts
- packages/splitmix64/library.json
- packages/splitmix64/splitmix64-1.0.1.d.ts
- packages/splitmix64/splitmix64.d.ts
- packages/webgl_memory/library.json
- packages/webgl_memory/webgl_memory-0.0.1.d.ts
- packages/webgl_memory/webgl_memory.d.ts
Contributing some comparatively simple ones.
- [vibrate](https://github.com/adamwestman/extension-vibrate)
- [JsToDef](https://github.com/AGulev/jstodef)
- [pcgrandom](https://github.com/selimanac/defold-random)
- [review](https://github.com/defold/extension-review)
- [splitmix64](https://github.com/indiesoftby/defold-splitmix64)
- [webgl_memory](https://github.com/indiesoftby/defold-webgl-memory)
> Add vibrate, JsToDef, pcgrandom, review, splitmix64, webgl_memory

- packages/persist/library.json
- packages/persist/persist-0.0.1.d.ts
- packages/persist/persist.d.ts
Adds [persist](https://github.com/klaytonkowalski/library-defold-persist)
> Add persist

- packages/TapticEngine/TapticEngine-1.2.d.ts
- packages/TapticEngine/TapticEngine.d.ts
- packages/TapticEngine/library.json
- packages/defold-clipboard/defold-clipboard-1.24.0.d.ts
- packages/defold-clipboard/defold-clipboard.d.ts
- packages/defold-clipboard/library.json
- packages/poki-sdk/library.json
- packages/poki-sdk/poki-sdk-1.5.0.d.ts
- packages/poki-sdk/poki-sdk.d.ts
Adds:
- [def_taptic_engine](https://github.com/MaratGilyazov/def_taptic_engine)
- [defold-clipboard](https://github.com/britzl/defold-clipboard)
- [poki-sdk](https://github.com/defold/extension-poki-sdk)
> Adds def_taptic_engine, defold-clipboard, poki-sdk

- packages/defold-prng/library.json
- packages/defold-prng/prng-1.0.2.d.ts
- packages/defold-prng/prng.d.ts
- packages/extension-pcgrandom/library.json
- packages/extension-pcgrandom/pcgrandom-0.0.1.d.ts
- packages/extension-pcgrandom/pcgrandom.d.ts
- packages/extension-sfmtrandom/library.json
- packages/extension-sfmtrandom/sfmtrandom-0.0.1.d.ts
- packages/extension-sfmtrandom/sfmtrandom.d.ts
Adds:
- [defold-prng](https://github.com/thinknathan/defold-prng)
- [extension-sfmtrandom](https://github.com/Lerg/extension-sfmtrandom)
- [extension-pcgrandom](https://github.com/Lerg/extension-pcgrandom) (different from the existing pcgrandom extension)
> Add defold-prng, extension-sfmtrandom, extension-pcgrandom

- packages/scene3d/library.json
- packages/scene3d/scene3d-1.2.0.d.ts
- packages/scene3d/scene3d.d.ts
Adds [scene3d](https://github.com/indiesoftby/defold-scene3d)
> Add scene3d

- packages/imgui/imgui-1.3.2.d.ts
- packages/imgui/imgui.d.ts
- packages/imgui/library.json
- packages/lfs/lfs-1.1.0.d.ts
- packages/lfs/lfs.d.ts
- packages/lfs/library.json
- packages/netimgui/library.json
- packages/netimgui/netimgui-1.0.3.d.ts
- packages/netimgui/netimgui.d.ts
- packages/webrtc/library.json
- packages/webrtc/webrtc-0.0.1.d.ts
- packages/webrtc/webrtc.d.ts
Adds:
- [imgui](https://github.com/britzl/extension-imgui/)
- [netimgui](https://github.com/DreamRealityInteractive/extension-netimgui)
- [lfs](https://github.com/britzl/defold-lfs/)
- [webrtc](https://github.com/VitusVeit/extension-webrtc)
> Add imgui, netimgui, lfs, webrtc

- README.md
- packages/defold-orthographic/orthographic.camera.d.ts
- packages/defold-yagames/yagames.yagames.d.ts
- template/README.md
> Use undefined instead of null + fix typo

- packages/ironsource/ironsource-1.0.0.d.ts
- packages/ironsource/ironsource.d.ts
- packages/ironsource/library.json
- packages/yametrica/library.json
- packages/yametrica/yametrica-1.0.0.d.ts
- packages/yametrica/yametrica.d.ts
Adds [ironsource](https://github.com/defold/extension-ironsource), [yametrica](https://github.com/indiesoftby/defold-yametrica).
> Add ironsource, yametrica

- packages/defold-playable-ads/library.json
- packages/defold-playable-ads/mraid-1.4.1.d.ts
- packages/defold-playable-ads/mraid.d.ts
- packages/defold-yoga/library.json
- packages/defold-yoga/yoga-0.2.0.d.ts
- packages/defold-yoga/yoga.d.ts
- packages/extension-admob/admob-3.4.1.d.ts
- packages/extension-admob/admob.d.ts
- packages/extension-admob/library.json
- packages/extension-facebook/facebook-7.2.1.d.ts
- packages/extension-facebook/facebook.d.ts
- packages/extension-facebook/library.json
- packages/extension-firebase-analytics/firebase-3.0.0.d.ts
- packages/extension-firebase-analytics/firebase.d.ts
- packages/extension-firebase-analytics/library.json
- packages/extension-gpgs/gpgs-3.0.2.d.ts
- packages/extension-gpgs/gpgs.d.ts
- packages/extension-gpgs/library.json
- packages/extension-iap/iap.d.ts
- packages/extension-push/library.json
- packages/extension-push/push-4.0.1.d.ts
- packages/extension-push/push.d.ts
- packages/extension-steam/library.json
- packages/extension-steam/steam-0.0.1.d.ts
- packages/extension-steam/steam.d.ts
- packages/extension-websocket/library.json
- packages/extension-websocket/websocket-3.1.0.d.ts
- packages/extension-websocket/websocket.d.ts
Adds
- defold-playable-ads
- defold-yoga
- extension-admob
- extension-facebook
- extension-firebase-analytics
- extension-gpgs
- extension-push
- extension-steam
- extension-websocket
> Add 9 extensions

- packages/extension-adinfo/adinfo-3.0.2.d.ts
- packages/extension-adinfo/adinfo.d.ts
- packages/extension-adinfo/library.json
- packages/extension-cas/cas-0.0.1.d.ts
- packages/extension-cas/cas.d.ts
- packages/extension-cas/library.json
- packages/extension-crypt/crypt-1.1.0.d.ts
- packages/extension-googleplayinstant/instantapp-1.0.3.d.ts
- packages/extension-googleplayinstant/instantapp.d.ts
- packages/extension-googleplayinstant/library.json
- packages/extension-iac/iac-1.2.4.d.ts
- packages/extension-iac/iac.d.ts
- packages/extension-iac/library.json
- packages/extension-kaiads/kaiads-1.1.2.d.ts
- packages/extension-kaiads/kaiads.d.ts
- packages/extension-kaiads/library.json
- packages/extension-siwa/library.json
- packages/extension-siwa/siwa-1.1.2.d.ts
- packages/extension-siwa/siwa.d.ts
- packages/extension-zendesk/library.json
- packages/extension-zendesk/zendesk-1.0.0.d.ts
- packages/extension-zendesk/zendesk.d.ts
Updates crypt
Adds:
- adinfo
- cas
- instantapp
- iac
- kaiads
- siwa
- zendesk
> Update crypt + add 7 new packages

- packages/defold-event/event-0.0.1.d.ts
- packages/defold-event/event.event.d.ts
- packages/defold-event/library.json
- packages/defold-log/library.json
- packages/defold-log/log-0.0.2.d.ts
- packages/defold-log/log.log.d.ts
- packages/defold-tweener/library.json
- packages/defold-tweener/tweener-0.0.1.d.ts
- packages/defold-tweener/tweener.tweener.d.ts
- packages/narrator/narrator.narrator.d.ts
Adds
- [event](https://github.com/Insality/defold-event)
- [log](https://github.com/Insality/defold-log)
- [tweener](https://github.com/Insality/defold-tweener)
> Add event, log, tweener

- packages/AppLovin-MAX-Defold/applovin-1.1.0.d.ts
- packages/AppLovin-MAX-Defold/applovin.d.ts
- packages/AppLovin-MAX-Defold/library.json
Adds [applovin](https://github.com/AppLovin/AppLovin-MAX-Defold)
> Add applovin

- packages/defold-screenshot/library.json
- packages/defold-screenshot/screenshot-1.9.1.d.ts
- packages/defold-screenshot/screenshot.d.ts
Adds [screenshot](https://github.com/britzl/defold-screenshot)
> Add screenshot

- packages/defold-sharing/library.json
- packages/defold-sharing/share-4.3.1.d.ts
- packages/defold-sharing/share.d.ts
Adds [sharing](https://github.com/britzl/defold-sharing)
> Add sharing

- packages/extension-permissions/library.json
- packages/extension-permissions/permissions-1.0.0.d.ts
- packages/extension-permissions/permissions.d.ts
Adds [extension-permissions](https://github.com/defold/extension-permissions)
> Add extension-permissions

- packages/LuaScriptInstance/library.json
- packages/LuaScriptInstance/lua_script_instance-0.1.1.d.ts
- packages/LuaScriptInstance/lua_script_instance.d.ts
- packages/extension-videoplayer-native/library.json
- packages/extension-videoplayer-native/videoplayer-1.0.1.d.ts
- packages/extension-videoplayer-native/videoplayer.d.ts
- packages/extension-videoplayer/library.json
- packages/extension-videoplayer/videoplayer-0.0.1.d.ts
- packages/extension-videoplayer/videoplayer.d.ts
Adds:
- LuaScriptInstance
- extension-videoplayer-native
- extension-videoplayer
> feat: add simple packages

- packages/defold-skippy/library.json
- packages/defold-skippy/skippy-1.0.0.d.ts
- packages/defold-skippy/skippy.d.ts
[Defold Skippy Extension](https://github.com/NaakkaDev/defold-skippy)
> feat: add Defold Skippy Extension

- packages/defold-apkx/apkx.d.ts
- packages/defold-simplex-noise/library.json
- packages/defold-simplex-noise/simplex-1.0.0.d.ts
- packages/defold-simplex-noise/simplex.d.ts
- packages/defold-zstd/library.json
- packages/defold-zstd/zstd-1.0.0.d.ts
- packages/defold-zstd/zstd.d.ts
- Adds [zstd](https://github.com/indiesoftby/defold-zstd) definitions
- Adds [simplex-noise](https://github.com/indiesoftby/defold-simplex-noise) definitions
- Fixes typo in defold-apkx definition
> feat: add zstd + simplex-noise definitions
